apps/reviews/urls.py
from django.urls import path
from .views import show_agent_dashboard, show_dashboard, ticket_assignment_dashboard, assignment_rule_list, create_assignment_rule, create_ticket_assignment, ticket_assignment_list,create_ticket_review,change_scorecard, show_review, save_review, create_category, create_scorecard, list_categories, list_scorecards, list_reviews, view_category, view_scorecard, create_ticket_assignment_add_filter

urlpatterns = [
    path('create-ticket-review/<str:ticket_id>/', create_ticket_review, name='create_ticket_review'),
    path('review/<str:review_id>/', show_review, name='show_review'),
    path('review/<str:review_id>/edit', change_scorecard, name='edit_review'),
    path('review/<str:review_id>/save', save_review, name='save_review'),
    path('categories/', list_categories, name='list_categories'),
    path('scorecards/', list_scorecards, name='list_scorecards'),
    path('categories/new', create_category, name='create_category'),
    path('scorecards/new', create_scorecard, name='create_scorecard'),
    path('reviews/new/<str:ticket_id>/', create_ticket_review, name='create_review'),
    path('', list_reviews, name='list_reviews'), 
    path('categories/<str:category_id>/', view_category, name='view_category'),  # Add this line
    path('scorecards/<str:scorecard_id>/', view_scorecard, name='view_scorecard'),  # Add this line
    path('assignment_dashboard/', ticket_assignment_list, name='ticket_assignment_dashboard'),
    path('assignment-rules/', assignment_rule_list, name='assignment_rule_list'),
    path('assignment-rules/new/', create_assignment_rule, name='create_assignment_rule'),
    path('ticket-assignments/', ticket_assignment_list, name='ticket_assignment_list'),
    path('ticket-assignments/new/', create_ticket_assignment, name='create_ticket_assignment'),
    path('ticket-assignments/new/add_filter', create_ticket_assignment_add_filter, name='create_ticket_assignment_add_filter'),
    path('dashboard/', show_dashboard, name='show_dashboard'),
    path('agent/dashboard/', show_agent_dashboard, name='show_agent_dashboard'),
]

limuza/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.views.generic.base import TemplateView

import debug_toolbar

from limuza import views
# ADDED BY SMARTDEV CODE

admin.autodiscover()


urlpatterns = [
    path("", views.HomeView.as_view(), name='home'),
    # ADDED BY SMARTDEV-CODE 08/16/2024
    path('accounts/login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('admin/', admin.site.urls),
    path('workspace/', include('apps.customer_accounts.urls')),
    path('tickets/', include('apps.tickets.urls')),
    path('reviews/', include('apps.reviews.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path("accounts/", include("allauth.urls")),
    path("invitations/", include('invitations.urls', namespace='invitations')),
    # path("accounts/profile/", TemplateView.as_view(template_name="profile.html"), name='profile'),
    path("i18n/", include("django.conf.urls.i18n")),

    # New paths
    path("reviews/", TemplateView.as_view(template_name="index.html"), name='reviews'),
    path("coaching/", TemplateView.as_view(template_name="index.html"), name='coaching'),
    path("assignments/", TemplateView.as_view(template_name="index.html"), name='assignments'),
    path("conversations/", TemplateView.as_view(template_name="index.html"), name='conversations'),
    # for dev reloading
    path("__reload__/", include("django_browser_reload.urls"))
]

apps/reviews/models.py
# this got very complicated very quickly lol. This is the brief explanation:
# categories make up scorecards, but they don't have to be and not with the same weighting
# To different departments, tone can mean more than another as an example but we don't want 2 tone categories - ScorecardCategory solves this
# They can be used in multiple.
# 
# Reviews can be done on two levels, tickets and conversations so we should be able to do this now already.
# ReviewCategory solves the fact that categories are the "bases" and the actual values should be related to a review
# Category: Defines scales and N/A option.
# Scorecard: Represents a scorecard with related categories.
# ScorecardCategory: Links scorecards to categories with additional fields like weighting.
# Review: Base class for reviews, with methods to check review type.
# TicketReview: Inherits from Review and links to Ticket.
# ConversationReview: Inherits from Review and links to Conversation.
# ReviewCategory: Stores category evaluations within a review.
from django.contrib.auth import get_user_model

from django.conf import settings
from django.db import models
from django_multitenant.models import TenantModel

from apps.tickets.models import Ticket, Conversation
from apps.customer_accounts.models import Workspace, TenantClass, TenantForeignKey 

User = get_user_model()


class Category(TenantModel):
    SCALE_CHOICES = [
        ('binary', 'Binary'),
        ('3_point', '3 Point'),
        ('5_point', '5 Point'),
        ('7_point', '7 Point'),
    ]

    name = models.CharField(max_length=255)
    scale = models.CharField(max_length=50, choices=SCALE_CHOICES)
    allow_na = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
    def to_json(self):
        return {
            'id': self.id,
            'name': self.name,
            'scale': self.scale,
            'allow_na': self.allow_na,
        }

class Scorecard(TenantClass):
    name = models.CharField(max_length=255)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='scorecards')
    workspace = TenantForeignKey(Workspace, on_delete=models.CASCADE, related_name='workspace')

    def __str__(self):
        return self.name
    
    def to_json(self):
        return {
            'id': self.id,
            'name': self.name,
        }
    
    def get_categories(self):
        return ScorecardCategory.objects.filter(scorecard=self).select_related('category')

class ScorecardCategory(TenantClass):
    scorecard = TenantForeignKey(Scorecard, on_delete=models.CASCADE, related_name='scorecard_categories')
    category = TenantForeignKey(Category, on_delete=models.CASCADE, related_name='scorecard_categories')
    weighting = models.FloatField(default=1.0)

    class Meta:
        unique_together = ('scorecard', 'category')

    def __str__(self):
        return f"{self.scorecard.name} - {self.category.name}"
    
    def to_json(self):
        return {
            'id': self.id,
            'scorecard': self.scorecard.to_json(),
            'category': self.category.to_json(),
            'weighting': self.weighting
        }

class Review(TenantClass):
    scorecard = TenantForeignKey(Scorecard, on_delete=models.CASCADE, related_name='reviews')
    reviewer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='reviews')
    agent = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='reviews_received')
    date = models.DateTimeField(auto_now_add=True)
    draft = models.BooleanField(default=True)  # Added field for draft status
    comments = models.TextField()

    def is_ticket_review(self):
        return hasattr(self, 'ticketreview')

    def is_conversation_review(self):
        return hasattr(self, 'conversationreview')
    
    def get_review_data(self):
        """
        Retrieves the necessary data for the review form.
        If there are review categories, return those.
        Otherwise, return the scorecard categories for the scorecard linked to the review.
        """
        review_categories = self.review_categories.all().select_related('scorecard_category__category')
        if review_categories.exists():
            review_data = [rc.to_json() for rc in review_categories]
            scorecard_categories = None
        else:
            scorecard_categories = self.scorecard.get_categories()
            review_data = [sc.to_json() for sc in scorecard_categories]
            review_categories = None
        return review_data, scorecard_categories, review_categories
    
    def get_categories(self):
        rc = ReviewCategory.objects.filter(review=self).select_related('scorecard_category__category')
        if rc.exists():
            return rc
        else:
            return self.scorecard.get_categories()

    def update_scorecard(self, scorecard):
        # update/save the scorecard, returns all scorecard_categories
        self.scorecard = scorecard
        self.save()
        return self.get_categories()

    def __str__(self):
        return f"Review {self.id}"

class TicketReview(Review):
    ticket = TenantForeignKey(Ticket, on_delete=models.CASCADE, related_name='ticket_reviews')

class ConversationReview(Review):
    conversation = TenantForeignKey(Conversation, on_delete=models.CASCADE, related_name='conversation_reviews')

class ReviewCategory(TenantClass):
    review = TenantForeignKey(Review, on_delete=models.CASCADE, related_name='review_categories')
    scorecard_category = TenantForeignKey(ScorecardCategory, on_delete=models.CASCADE, related_name='review_categories')
    score = models.IntegerField(null=True, blank=True)  # Assuming the score is an integer
    na = models.BooleanField(default=False)

    class Meta:
        unique_together = ('review', 'scorecard_category')

    def __str__(self):
        return f"{self.review.id} - {self.scorecard_category.category.name}"

    def to_json(self):
        sc = self.scorecard_category
        return {
            'id': self.id,
            'score': self.score,
            'na': self.na,
            'scorecard_category': sc.to_json()
        }

class AssignmentRule(TenantClass):
    # TODO create methods that will create ticket assignments on a regular basis automatically.
    name = models.CharField(max_length=255)
    reviewers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='assignment_rules')
    description = models.TextField()
    criteria = models.JSONField() 

    def __str__(self):
        return self.name

class TicketAssignment(TenantClass):
    STATUS_CHOICES = [
        ('not_started', 'Not Started'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
    ]

    assignment_rule = TenantForeignKey(AssignmentRule, on_delete=models.CASCADE, related_name='ticket_assignments')
    reviewer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='ticket_assignments')
    reviews = models.ManyToManyField('reviews.Review', related_name='ticket_assignments')
    completion_percentage = models.FloatField(default=0.0)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='not_started')
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return f"{self.assignment_rule.name} - {self.reviewer.username} - {self.status}"

class AssignmentDashboard(models.Model):
    manager = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='managed_dashboards')

    def get_ticket_assignments(self):
        return TicketAssignment.objects.all()

    def get_user_workload(self, user):
        return TicketAssignment.objects.filter(agent=user).count() + TicketAssignment.objects.filter(reviewer=user).count()

    def adjust_assignment_rules(self, rule_id, new_criteria):
        rule = AssignmentRule.objects.get(id=rule_id)
        rule.criteria = new_criteria
        rule.save()
        return rule

    def __str__(self):
        return f"Dashboard for manager {self.manager.username}"

        return f"Dashboard for manager {self.manager.username}"

apps/reviews/forms.py
from django import forms
from .models import *

class SelectScorecardForm(forms.Form):
    scorecard = forms.ModelChoiceField(queryset=Scorecard.objects.all(), required=True,initial=0)

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['comments']
        widgets = {
            'comments': forms.Textarea(attrs={'class': 'textarea textarea-bordered w-full'}),
        }

    def __init__(self, *args, **kwargs):
        review_data = kwargs.pop('review_data', [])
        super().__init__(*args, **kwargs)

        for item in review_data:
            if isinstance(item, ReviewCategory):
                category = item.scorecard_category.category.to_json()
                score = item.score
                na = item.na
            else:
                category = item.category.to_json()
                score = None
                na = item.category.allow_na

            field_name = f'category_{category["id"]}'
            try:
                scale_limit = int(category['scale'][0])
            except (ValueError, TypeError):
                scale_limit = 7  # Default scale limit if parsing fails

            self.fields[field_name] = forms.IntegerField(
                label=category['name'],
                initial=score,
                required=not category['allow_na'],
                widget=forms.NumberInput(attrs={'type': 'range', 'min': 0, 'max': 100, 'step': 25, 'class': 'range w-full'})
            )

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'scale', 'allow_na']
        widgets = {
            'scale': forms.Select(choices=Category.SCALE_CHOICES),
        }

class ScorecardForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Scorecard
        fields = ['name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.weight_fields = {}
        for category in self.fields['categories'].queryset:
            field_name = f'weight_{category.id}'
            self.fields[field_name] = forms.FloatField(
                initial=1.0,
                required=False,
                label=f'Weight for {category.name}'
            )
            self.weight_fields[category.id] = self[field_name]

class ScorecardCategoryForm(forms.ModelForm):
    class Meta:
        
        model = ScorecardCategory
        fields = ['category', 'weighting']
        widgets = {
            'weighting': forms.NumberInput(attrs={'step': 0.1, 'min': 0, 'max': 10}),
        }

class AssignmentRuleForm(forms.ModelForm):
    class Meta:
        model = AssignmentRule
        fields = ['name', 'reviewers', 'description', 'criteria']
        widgets = {
            'reviewers': forms.CheckboxSelectMultiple,
        }

class TicketAssignmentForm(forms.ModelForm):
    class Meta:
        model = TicketAssignment
        fields = ['assignment_rule', 'reviewer', 'reviews', 'start_date', 'end_date']
        widgets = {
            'assignment_rule': forms.Select(attrs={
                'class': 'rounded-lg p-3 border border-base-100 block w-80 text-sm bg-base-300',
                'placeholder': 'Assignment Rule'
            }),
            'reviewer': forms.Select(attrs={
                'class': 'rounded-lg p-3 border border-base-100 block w-80 text-sm bg-base-300'
            }),
            'reviews': forms.CheckboxSelectMultiple(attrs={
                'class': 'rounded-lg'
            }),
            'start_date': forms.DateInput(attrs={
                'class': 'rounded-lg p-3 bg-base-300 border border-base-100 block w-60 text-sm pl-10',
                'placeholder': 'Select date',
                'datepicker': 'true'
            }),
            'end_date': forms.DateInput(attrs={
                'class': 'rounded-lg p-3 bg-base-300 border border-base-100 block w-60 text-sm pl-10',
                'placeholder': 'Select date',
                'datepicker': 'true'
            }),
        }

apps/reviews/views/categories.py
from django.shortcuts import render, redirect, get_object_or_404
from apps.reviews.models import TicketReview, ReviewCategory, Category
from django.contrib.auth.decorators import login_required
from apps.reviews.models import TicketReview, Scorecard
from apps.tickets.models import Ticket
from django.contrib.auth import get_user_model
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.utils import timezone
from ..forms import *
from ..models import *

User = get_user_model()

@login_required
def list_categories(request):
    categories = Category.objects.all()
    return render(request, 'categories/list_categories.html', {'categories': categories})

@login_required
def create_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Category created successfully.')
            return redirect('list_categories')
    else:
        form = CategoryForm()

    context = {
        'form': form
    }
    return render(request, 'categories/create_category.html', context)

@login_required
def view_category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    return render(request, 'view_category.html', {'category': category})

apps/reviews/templates/reviews/_review_view.html
<div id ='review_container'>
    <h3 class="text-lg font-bold mb-4">Scorecard</h3>
    <form method="post" id="scorecard-form" hx-post="{% url 'edit_review' review.id %}" hx-trigger="change" hx-target="#review_container">
        {% csrf_token %}
        <div class="form-control mb-4">
            <label class="label" for="id_scorecard">
                <span class="label-text">Select Scorecard</span>
            </label>
            {{ scorecard_form.scorecard }}
            <input type="hidden" name="select_scorecard" value="true">
        </div>
    </form>
    <form method="post" action="{% url 'save_review' review.id %}">
        {% csrf_token %}
        {% for field in form %}
            {% if field.name not in "comments scorecard" %}
                <div class="form-group mb-4">
                    <label class="label" for="{{ field.id_for_label }}">
                        <span class="label-text">{{ field.label }}</span>
                    </label>
                    {{ field }}
                    <div class="w-full flex justify-between text-xs px-2">
                        <span>|</span>
                        <span>|</span>
                        <span>|</span>
                        <span>|</span>
                        <span>|</span>
                    </div>
                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                </div>
            {% endif %}
        {% endfor %}
        <div class="form-group mb-4">
            <label class="label" for="id_comments">
                <span class="label-text">Comments</span>
            </label>
            {{ form.comments }}
        </div>
        <div class="mt-4">
            <button type="submit" class="btn btn-primary w-full">Save Review</button>
        </div>
    </form>
</div>

apps/reviews/templates/reviews/_ticket_review_data.html
{% if ticket %}
<div id="ticket-data-view" class="flex flex-col h-full">
    <div class="flex-1 flex flex-col overflow-y-auto bg-white shadow rounded">
        <div class="mb-4 flex-1 flex flex-col">
            <div role="tablist" class="tabs items-stretch tabs-md tabs-lifted ">
                <input type="radio" name="ticket_tabs" id="tab1" role="tab" class="tab" aria-label="Conversation Data" checked />
                <div id="content1" role="tabpanel" class="flex-1  items-stretch tab-content bg-base-100 border-base-300 rounded-box p-6 overflow-hidden">
                    <h3 class="text-lg font-bold">Conversation Data</h3>
                    <p class="truncate">Participants: {{ ticket.agent.username }}</p>
                    <p class="truncate">Assignee: {{ ticket.agent.username }}</p>
                    <p class="truncate">Freshdesk ID: {{ ticket.external_id }}</p>
                    <p class="truncate">Email: {{ ticket.agent.email }}</p>
                    <p class="truncate">Channel: portal</p>
                    <p class="truncate">Status: {{ ticket.status }}</p>
                    <p class="truncate">Priority: {{ ticket.ticket_data.priority }}</p>
                    <p class="truncate">Tags: Driver Theft</p>
                    <p class="truncate">Group: Customer Support - US</p>
                </div>
                
                <input type="radio" name="ticket_tabs" id="tab2" role="tab" class="tab" aria-label="Data 2" />
                
                <input type="radio" name="ticket_tabs" id="tab3" role="tab" class="tab" aria-label="Stats" />
                

                
                <div id="content2" role="tabpanel" class="tab-content w-full bg-base-100 border-base-300 rounded-box p-6 hidden">
                    <h3 class="text-lg font-bold">Data 2</h3>
                    <!-- Add more data as needed -->
                </div>
                
                <div id="content3" role="tabpanel" class="tab-content w-full bg-base-100 border-base-300 rounded-box p-6 hidden">
                    <h3 class="text-lg font-bold">Stats</h3>
                    <!-- Add more stats as needed -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}

apps/reviews/templates/reviews/create_review.html
{% extends "base.html" %}

{% block content %}
<div class="container mx-auto p-4">
    <h1 class="text-2xl font-bold mb-4">Create Review</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="ticket_id" value="{{ ticket.id }}">
        <div class="mt-4">
            <button type="submit" class="btn btn-primary w-full">Next</button>
        </div>
    </form>
</div>
{% endblock %}

apps/reviews/templates/reviews/list_reviews.html
{% extends "base.html" %}

{% block content %}
<div class="container mx-auto p-4">
    <h1 class="text-2xl font-bold mb-4">Reviews</h1>
    <table class="table-auto w-full">
        <thead>
            <tr>
                <th class="px-4 py-2">Review ID</th>
                <th class="px-4 py-2">Ticket Subject</th>
                <th class="px-4 py-2">Scorecard</th>
                <th class="px-4 py-2">Reviewer</th>
                <th class="px-4 py-2">Agent</th>
                <th class="px-4 py-2">Date</th>
            </tr>
        </thead>
        <tbody>
            {% for review in reviews %}
            <tr class="cursor-pointer" onclick="window.location='{% url 'show_review' review.id %}'">
                <td class="border px-4 py-2">{{ review.id }}</td>
                <td class="border px-4 py-2">{{ review.ticket.subject }}</td>
                <td class="border px-4 py-2">{{ review.scorecard.name }}</td>
                <td class="border px-4 py-2">{{ review.reviewer.username }}</td>
                <td class="border px-4 py-2">{{ review.agent.username }}</td>
                <td class="border px-4 py-2">{{ review.date }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

apps/reviews/templates/reviews/show_review.html
{% extends "base.html" %}

{% block content %}
<div class="flex h-full">
    <div id="ticket-data" class="w-1/4 min-w-[200px] bg-gray-100 p-4 overflow-y-auto">
        {% include 'reviews/_ticket_review_data.html' %}
    </div>
    <div id="ticket-view" class="w-1/2 bg-gray-200 p-4 overflow-y-auto">
        {% include '_ticket_view.html' %}
    </div>
    <div id="scorecard-view" class="w-1/4 min-w-[200px] bg-white p-4 overflow-y-auto">
        {% include 'reviews/_review_view.html' %}
    </div>
</div>
{% endblock %}